version: "3"
services:
    api:
        build: .
        environment:
            DATABASE_URL: postgresql://nile@db:5432/nile
        ports: ["80:80"]
        volumes:
            - ./api:/app/api
        depends_on:
            - db
    db:
        image: postgres:12.0-alpine
        environment:
            - POSTGRES_USER=nile
            - POSTGRES_DB=nile
    migrate:
        build: .
        environment:
            PYTHONPATH: .
            DATABASE_URL: postgresql://nile@db:5432/nile
        volumes:
            - ./alembic:/app/alembic
            - ./alembic.ini:/app/alembic.ini
            - ./api:/app/api
        depends_on:
            - db
        command: alembic upgrade head
        # command: alembic revision --autogenerate

        

